webtalk_init -webtalk_dir E:\\Soc\\Lab3\\xup\\embedded\\2015_2_zynq_labs\\lab_1\\lab_1.sdk\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2020-12-05 15:19:29" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2018.1" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2018.1" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "212091324_0_0_015" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "576m9ql7ujfn2un1ec3i3h1c4l" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2018.1_2" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "2" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-5650U CPU @ 2.20GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2200 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.488 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1607152536442" -context "sdk\\\\bsp/1607152536442"
webtalk_add_data -client sdk -key hwid -value "1607151275259" -context "sdk\\\\bsp/1607152536442"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1607152536442"
webtalk_add_data -client sdk -key apptemplate -value "memory_tests" -context "sdk\\\\bsp/1607152536442"
webtalk_add_data -client sdk -key RecordType -value "BSPCreation" -context "sdk\\\\bsp/1607152536442"
webtalk_add_data -client sdk -key uid -value "1607152541822" -context "sdk\\\\application/1607152541822"
webtalk_add_data -client sdk -key hwid -value "1607151275259" -context "sdk\\\\application/1607152541822"
webtalk_add_data -client sdk -key bspid -value "1607152536442" -context "sdk\\\\application/1607152541822"
webtalk_add_data -client sdk -key newbsp -value "true" -context "sdk\\\\application/1607152541822"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1607152541822"
webtalk_add_data -client sdk -key apptemplate -value "memory_tests" -context "sdk\\\\application/1607152541822"
webtalk_add_data -client sdk -key RecordType -value "APPCreation" -context "sdk\\\\application/1607152541822"
webtalk_add_data -client sdk -key LangUsed -value "C" -context "sdk\\\\application/1607152541822"
webtalk_add_data -client sdk -key Procused -value "ps7_cortexa9" -context "sdk\\\\application/1607152541822"
webtalk_add_data -client sdk -key projSize -value "252.6875" -context "sdk\\\\application/1607152541822"
webtalk_add_data -client sdk -key uid -value "NA" -context "sdk\\\\bsp/1607152769695"
webtalk_add_data -client sdk -key RecordType -value "ToolUsage" -context "sdk\\\\bsp/1607152769695"
webtalk_add_data -client sdk -key BootgenCount -value "0" -context "sdk\\\\bsp/1607152769695"
webtalk_add_data -client sdk -key DebugCount -value "0" -context "sdk\\\\bsp/1607152769695"
webtalk_add_data -client sdk -key PerfCount -value "0" -context "sdk\\\\bsp/1607152769695"
webtalk_add_data -client sdk -key FlashCount -value "0" -context "sdk\\\\bsp/1607152769695"
webtalk_add_data -client sdk -key CrossTriggCount -value "0" -context "sdk\\\\bsp/1607152769695"
webtalk_add_data -client sdk -key QemuDebugCount -value "0" -context "sdk\\\\bsp/1607152769695"
webtalk_transmit -clientid 3023782731 -regid "212091324_0_0_015" -xml E:\\Soc\\Lab3\\xup\\embedded\\2015_2_zynq_labs\\lab_1\\lab_1.sdk\\webtalk\\usage_statistics_ext_sdk.xml -html E:\\Soc\\Lab3\\xup\\embedded\\2015_2_zynq_labs\\lab_1\\lab_1.sdk\\webtalk\\usage_statistics_ext_sdk.html -wdm E:\\Soc\\Lab3\\xup\\embedded\\2015_2_zynq_labs\\lab_1\\lab_1.sdk\\webtalk\\sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
