#stopwatch circuit, Summer 2021 HUST
### Nexys A7 Clock Oscillator:
# Clock - 100MHz oscillator on E3

set_property PACKAGE_PIN E3 [get_ports Clock]
set_property PACKAGE_PIN M17 [get_ports ControlButton]
set_property PACKAGE_PIN P18 [get_ports Reset]

set_property PACKAGE_PIN H15 [get_ports {Display[7]}]
set_property PACKAGE_PIN L18 [get_ports {Display[6]}]
set_property PACKAGE_PIN T11 [get_ports {Display[5]}]
set_property PACKAGE_PIN P15 [get_ports {Display[4]}]
set_property PACKAGE_PIN K13 [get_ports {Display[3]}]
set_property PACKAGE_PIN K16 [get_ports {Display[2]}]
set_property PACKAGE_PIN R10 [get_ports {Display[1]}]
set_property PACKAGE_PIN T10 [get_ports {Display[0]}]

set_property PACKAGE_PIN J14 [get_ports {Transistors[3]}]
set_property PACKAGE_PIN T9 [get_ports {Transistors[2]}]
set_property PACKAGE_PIN J18 [get_ports {Transistors[1]}]
set_property PACKAGE_PIN J17 [get_ports {Transistors[0]}]
set_property PACKAGE_PIN U13 [get_ports {Transistors[7]}]
set_property PACKAGE_PIN K2 [get_ports {Transistors[6]}]
set_property PACKAGE_PIN T14 [get_ports {Transistors[5]}]
set_property PACKAGE_PIN P14 [get_ports {Transistors[4]}]
set_property PULLUP true [get_ports {Transistors[7]}]
set_property PULLUP true [get_ports {Transistors[6]}]
set_property PULLUP true [get_ports {Transistors[5]}]
set_property PULLUP true [get_ports {Transistors[4]}]

set_property IOSTANDARD LVCMOS33 [get_ports ControlButton]
set_property IOSTANDARD LVCMOS33 [get_ports Reset]
set_property IOSTANDARD LVCMOS33 [get_ports {Display[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Display[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Display[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Display[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Display[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Display[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Display[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Display[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Transistors[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Transistors[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Transistors[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Transistors[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Transistors[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Transistors[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Transistors[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Transistors[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports Clock]

set_property IOSTANDARD LVCMOS33 [get_ports CLOCK]
set_property IOSTANDARD LVCMOS33 [get_ports DebouncedOuput]
set_property IOSTANDARD LVCMOS33 [get_ports InputPulse]
set_property PACKAGE_PIN M17 [get_ports DebouncedOuput]
