# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Xilinx/SHCodesign2021/lab2summer2021HUST_I2C/lab2ph2tmp101summer2021template/lab2ph2tmp101summer2021template.srcs/sources_1/ip/SystemClk60MHz/SystemClk60MHz.xci
# IP: The module: 'SystemClk60MHz' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Xilinx/SHCodesign2021/lab2summer2021HUST_I2C/lab2ph2tmp101summer2021template/lab2ph2tmp101summer2021template.srcs/sources_1/ip/SystemClk60MHz/SystemClk60MHz_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'SystemClk60MHz'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: c:/Xilinx/SHCodesign2021/lab2summer2021HUST_I2C/lab2ph2tmp101summer2021template/lab2ph2tmp101summer2021template.srcs/sources_1/ip/SystemClk60MHz/SystemClk60MHz.xdc
# XDC: The top module name and the constraint reference have the same name: 'SystemClk60MHz'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: c:/Xilinx/SHCodesign2021/lab2summer2021HUST_I2C/lab2ph2tmp101summer2021template/lab2ph2tmp101summer2021template.srcs/sources_1/ip/SystemClk60MHz/SystemClk60MHz_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'SystemClk60MHz'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# IP: c:/Xilinx/SHCodesign2021/lab2summer2021HUST_I2C/lab2ph2tmp101summer2021template/lab2ph2tmp101summer2021template.srcs/sources_1/ip/SystemClk60MHz/SystemClk60MHz.xci
# IP: The module: 'SystemClk60MHz' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Xilinx/SHCodesign2021/lab2summer2021HUST_I2C/lab2ph2tmp101summer2021template/lab2ph2tmp101summer2021template.srcs/sources_1/ip/SystemClk60MHz/SystemClk60MHz_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'SystemClk60MHz'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: c:/Xilinx/SHCodesign2021/lab2summer2021HUST_I2C/lab2ph2tmp101summer2021template/lab2ph2tmp101summer2021template.srcs/sources_1/ip/SystemClk60MHz/SystemClk60MHz.xdc
# XDC: The top module name and the constraint reference have the same name: 'SystemClk60MHz'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: c:/Xilinx/SHCodesign2021/lab2summer2021HUST_I2C/lab2ph2tmp101summer2021template/lab2ph2tmp101summer2021template.srcs/sources_1/ip/SystemClk60MHz/SystemClk60MHz_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'SystemClk60MHz'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
