# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Xilinx/SHCodesign2021/stopwatch2021summerlNexyA7/stopwatch2021summerlNexyA7.cache/wt [current_project]
set_property parent.project_path C:/Xilinx/SHCodesign2021/stopwatch2021summerlNexyA7/stopwatch2021summerlNexyA7.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {
  C:/Xilinx/SHCodesign2021/stopwatch2021summerlNexyA7/stopwatch2021summerlNexyA7.srcs/sources_1/imports/stopwatch_sources/DelayLoop.v
  C:/Xilinx/SHCodesign2021/stopwatch2021summerlNexyA7/stopwatch2021summerlNexyA7.srcs/sources_1/imports/stopwatch_sources/DisplayMuxNexysA7.v
  C:/Xilinx/SHCodesign2021/stopwatch2021summerlNexyA7/stopwatch2021summerlNexyA7.srcs/sources_1/imports/stopwatch_sources/PositiveClockedOneShot.v
  C:/Xilinx/SHCodesign2021/stopwatch2021summerlNexyA7/stopwatch2021summerlNexyA7.srcs/sources_1/imports/stopwatch_sources/Debouncer2020fall.v
  C:/Xilinx/SHCodesign2021/stopwatch2021summerlNexyA7/stopwatch2021summerlNexyA7.srcs/sources_1/imports/stopwatch_sources/Refreshing7SegNexysA7.v
  C:/Xilinx/SHCodesign2021/stopwatch2021summerlNexyA7/stopwatch2021summerlNexyA7.srcs/sources_1/imports/stopwatch_sources/UniversalCounter.v
  C:/Xilinx/SHCodesign2021/stopwatch2021summerlNexyA7/stopwatch2021summerlNexyA7.srcs/sources_1/imports/stopwatch_sources/SevenSegDriverNexysA7.v
  C:/Xilinx/SHCodesign2021/stopwatch2021summerlNexyA7/stopwatch2021summerlNexyA7.srcs/sources_1/imports/stopwatch_sources/StopwatchController2020fall.v
  C:/Xilinx/SHCodesign2021/stopwatch2021summerlNexyA7/stopwatch2021summerlNexyA7.srcs/sources_1/imports/stopwatch_sources/BCDto7Segment.v
  C:/Xilinx/SHCodesign2021/stopwatch2021summerlNexyA7/stopwatch2021summerlNexyA7.srcs/sources_1/imports/stopwatch_sources/Pulse10millisecond.v
  C:/Xilinx/SHCodesign2021/stopwatch2021summerlNexyA7/stopwatch2021summerlNexyA7.srcs/sources_1/imports/stopwatch_sources/Stopwatch2020FallNexysA7.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Xilinx/SHCodesign2021/stopwatch2021summerlNexyA7/stopwatch2021summerlNexyA7.srcs/constrs_1/imports/stopwatch2021summerlNexyA7/stopwatch2021summerNexyA7.xdc
set_property used_in_implementation false [get_files C:/Xilinx/SHCodesign2021/stopwatch2021summerlNexyA7/stopwatch2021summerlNexyA7.srcs/constrs_1/imports/stopwatch2021summerlNexyA7/stopwatch2021summerNexyA7.xdc]


synth_design -top Stopwatch2021summerNexysA7 -part xc7a100tcsg324-1


write_checkpoint -force -noxdef Stopwatch2021summerNexysA7.dcp

catch { report_utilization -file Stopwatch2021summerNexysA7_utilization_synth.rpt -pb Stopwatch2021summerNexysA7_utilization_synth.pb }
