# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Xilinx/SHCodesign2021/lab2summer2021HUST_I2C/UartTyperwriter2021summer/UartTyperwriter2021summer.cache/wt [current_project]
set_property parent.project_path C:/Xilinx/SHCodesign2021/lab2summer2021HUST_I2C/UartTyperwriter2021summer/UartTyperwriter2021summer.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:zybo-z7-10:part0:1.0 [current_project]
read_verilog -library xil_defaultlib {
  C:/Xilinx/SHCodesign2021/lab2summer2021HUST_I2C/UartTyperwriter2021summer/UartTyperwriter2021summer.srcs/sources_1/imports/UartTyperwriter2021summer/bbfifo_16x8.v
  C:/Xilinx/SHCodesign2021/lab2summer2021HUST_I2C/UartTyperwriter2021summer/UartTyperwriter2021summer.srcs/sources_1/imports/UartTyperwriter2021summer/kcuart_tx.v
  C:/Xilinx/SHCodesign2021/lab2summer2021HUST_I2C/UartTyperwriter2021summer/UartTyperwriter2021summer.srcs/sources_1/imports/UartTyperwriter2021summer/kcuart_rx.v
  C:/Xilinx/SHCodesign2021/lab2summer2021HUST_I2C/UartTyperwriter2021summer/UartTyperwriter2021summer.srcs/sources_1/imports/UartTyperwriter2021summer/BaudRateGenerator.v
  C:/Xilinx/SHCodesign2021/lab2summer2021HUST_I2C/UartTyperwriter2021summer/UartTyperwriter2021summer.srcs/sources_1/imports/UartTyperwriter2021summer/uart_rx.v
  C:/Xilinx/SHCodesign2021/lab2summer2021HUST_I2C/UartTyperwriter2021summer/UartTyperwriter2021summer.srcs/sources_1/imports/UartTyperwriter2021summer/uart_tx.v
  C:/Xilinx/SHCodesign2021/lab2summer2021HUST_I2C/UartTyperwriter2021summer/UartTyperwriter2021summer.srcs/sources_1/imports/UartTyperwriter2021summer/UARTmodule2021summer.v
  C:/Xilinx/SHCodesign2021/lab2summer2021HUST_I2C/UartTyperwriter2021summer/UartTyperwriter2021summer.srcs/sources_1/imports/UartTyperwriter2021summer/UartTyperwriter2021summer.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Xilinx/SHCodesign2021/lab2summer2021HUST_I2C/UartTyperwriter2021summer/UartTyperwriter2021summer.srcs/constrs_1/imports/UartTyperwriter2021summer/UartTyperwriter2021summer.xdc
set_property used_in_implementation false [get_files C:/Xilinx/SHCodesign2021/lab2summer2021HUST_I2C/UartTyperwriter2021summer/UartTyperwriter2021summer.srcs/constrs_1/imports/UartTyperwriter2021summer/UartTyperwriter2021summer.xdc]


synth_design -top UartTyperwriter2021summer -part xc7z010clg400-1


write_checkpoint -force -noxdef UartTyperwriter2021summer.dcp

catch { report_utilization -file UartTyperwriter2021summer_utilization_synth.rpt -pb UartTyperwriter2021summer_utilization_synth.pb }
