# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Xilinx/SHCodesign2021/detect011versions/detect011versions.cache/wt [current_project]
set_property parent.project_path C:/Xilinx/SHCodesign2021/detect011versions/detect011versions.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:zybo-z7-10:part0:1.0 [current_project]
read_verilog -library xil_defaultlib C:/Xilinx/SHCodesign2021/detect011versions/detect011versions.srcs/sources_1/imports/detect011versions/detect011withExpressions.v
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top detect011Expressions -part xc7z010clg400-1


write_checkpoint -force -noxdef detect011Expressions.dcp

catch { report_utilization -file detect011Expressions_utilization_synth.rpt -pb detect011Expressions_utilization_synth.pb }
